FROM nginx:1.14.2

COPY nginx.conf /etc/nginx/nginx.conf
COPY volume /srv/
RUN mkdir -p /data/www && chown www-data:www-data /data/www
RUN mkdir -p /data/www_temp && chown www-data:www-data /data/www_temp

WORKDIR "/srv"
CMD ["/srv/volume"]